### ISSUE TITLE
rel=noopener

### ISSUE THREAD

**Issue by niteshkumar2000** [sevenwik/portfolio#1]
https://github.com/sevenwik/portfolio/blob/92c2c901a96073741f6746e9fecf2057b9effa0e/src/components/About.js#L23

Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

Please change accordingly, because of these warnings automated CI deployments will fail!

**Comment by sevenwik** [comment]
Done boi
